language: node_js
node_js:
  - stable

sudo: required
dist: precise

cache:
  directories:
  - node_modules

script: make lint test

deploy:
  provider: npm
  skip_cleanup: true
  email: ildarrazin@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
