env:
  global:
    - CC_TEST_REPORTER_ID=456e7475eab866587f6268e775dc64810f4d104b693d6de4cadd6f768abeedf4

language: node_js
node_js:
  - stable

sudo: required

cache:
  directories:
  - node_modules

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: make lint test coverage

after_script:
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: npm
  skip_cleanup: true
  email: ildarrazin@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
